name: lint-and-test

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: npm install
    - run: npm run eslint
    - run: npm run stylelint
  test:
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        browser: [chrome]
        version: [stable]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
    - run: npm install
    - run: BROWSER=${{matrix.browser}} BVER=${{matrix.version}} ./node_modules/travis-multirunner/setup.sh
    - run: Xvfb :99 &
    - run: BROWSER=${{matrix.browser}} BVER=${{matrix.version}} DISPLAY=:99.0 npm run mocha -- --retries=3
